{
    'name': 'ADT Comercial',
    'version': '15.0.1.0.0',
    'author': 'Bigodoo',
    'maintainer': 'Bigodoo',
    'depends': [
        'base','sale', 'account', 'fleet','sms','mail','report_xlsx','adt_papeletas','contacto_addons'
    ],
    'data': [
        'data/sequences.xml',
        'data/recuperacion_data.xml',
        'data/action_view_sms.xml',
        'data/cron_notificaciones.xml',
        'data/cron_financiera.xml',
        'data/tipos_financiera_data.xml',
        'security/res_groups.xml',
        'security/res_groups_financiera.xml',
        'security/ir.model.access.csv',
        'views/view_comercial_socios.xml',
        'views/view_comercial_financiera.xml',
        'views/view_comercial_cuentas.xml',
        'views/view_comercial_cuentas_financiera.xml',
        'views/view_reporte_financiera.xml',
        'data/comercial_financiera_menu_sync.xml',
        'views/view_comercial_payments.xml',
        'views/view_comercial_registrar_mora.xml',
        'views/view_comercial_registrar_observacion.xml',
        'views/view_comercial_refinanciamiento.xml',
        'views/view_cobranzas_pagos.xml',
        'views/view_comercial_cuotas_pendientes.xml',
        'views/view_cobranzas_capturas.xml',
        'views/view_cobranzas_config.xml',
        'views/view_vehiculo.xml',
        'views/view_warning_message.xml',
        'reports/external_layout_cronograma.xml',
        # 'reports/paperformat.xml',
        'reports/report.xml',
        'reports/reporte_cronograma_cuenta.xml',
        'views/view_cronograma_tramos_wizard.xml',
        'views/view_cuotas_masivas.xml',
        'views/view_egresos_caja.xml',
        'views/dashboard_caja.xml',
        'views/dashboard_cobranzas.xml',
        'views/report.xml',
        'views/view_mobile_models.xml',
        'views/view_mobile_product_catalog.xml',
        'views/view_mobile_customers.xml',
        'views/view_notificacion_masiva_wizard.xml',
        'views/view_mobile_benefits.xml',
        'views/view_mobile_home_preview.xml',
        'data/mobile_benefit_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'adt_comercial/static/src/scss/style.scss',
            'adt_comercial/static/src/js/image_carousel_widget.js',
            'adt_comercial/static/src/js/fin_pct_bar_widget.js',
            'adt_comercial/static/src/js/mobile_home_preview_action.js',
        ],
        'web.assets_qweb': [
            'adt_comercial/static/src/xml/image_carousel.xml',
            'adt_comercial/static/src/xml/mobile_home_preview.xml',
        ],
    },
}
