from . import horario_slot
from . import mantenimiento_regla
from . import oferta
from . import vehicle_rule_state
from . import vehicle_report_status
from . import orden_atencion
from . import notification_campaign
from . import mobile_notification_extend
from . import fleet_vehicle
from . import traccar_client
from . import cron_service
from . import res_config_settings
